""" Pyramid Blending

This file has a number of functions that you need to fill out in order to
complete the assignment. Please write the appropriate code, following the
instructions on which functions you may or may not use.

References
----------
See the following papers, available on the course website under Reading Materials:

(1) "The Laplacian Pyramid as a Compact Image Code"
        Burt and Adelson, 1983

(2) "A Multiresolution Spline with Application to Image Mosaics"
        Burt and Adelson, 1983

Notes
-----
    You may NOT use cv2.pyrUp or cv2.pyrDown anywhere in this assignment.

GENERAL RULES:
    1. DO NOT INCLUDE code that saves, shows, displays, writes the image that
    you are being passed in. Do that on your own if you need to save the images
    but these functions should NOT save the image to disk.

    2. DO NOT import any other libraries aside from those that we provide.
    You should be able to complete the assignment with the given libraries
    (and in many cases without them).

    3. DO NOT change the format of this file. You may NOT change function
    type signatures (not even named parameters with defaults). You may add
    additional code to this file at your discretion, however it is your
    responsibility to ensure that the autograder accepts your submission.

    4. This file has only been tested in the course environment for this term.
    You are responsible for ensuring that your code executes properly in the
    course environment, and that any changes you make outside the
    areas annotated for student code do not impact your performance on the
    autograder system.
"""
import numpy as np
import scipy as sp
import scipy.signal  # one option for a 2D convolution library
import cv2


def returnYourName():
    """ When it is called, this function should return your official name as
    shown on your Gradescope Account. If you are not sure what name to use, 
    when you submit this file to Gradescope, the autograder will print an 
    error message with your name.

    Returns
    -------
    output : string formatted as follows: your official name in Gradescope
    """
    # WRITE YOUR CODE HERE.
    
    return 'SeungHui Huh'
    # End of code
    raise NotImplementedError


def generatingKernel(a):
    """Return a 5x5 filter based on a 5-element input vector and a generating parameter 
    (i.e., makes a square "5-tap" filter.) 

    Parameters 
    ----------
    a : float
        The kernel generating parameter in the range [0, 1] used to generate a
        5-tap filter kernel. The 5-tap kernel is 1D with 5 elements.

    Returns
    -------
    output : numpy.ndarray
        A 5x5 array generated by taking the outer product (kernel x kernel)
    """
    # DO NOT CHANGE THE CODE IN THIS FUNCTION
    
    # generate the 5-tap kernel
    kernel = np.array([0.25 - a / 2.0, 0.25, a, 0.25, 0.25 - a / 2.0])
    # use outer product of 2 vectors to generate the square filter
    return np.outer(kernel, kernel)


def reduce_layer(image, kernel=generatingKernel(0.4)):
    """Convolve the input image with a generating kernel filter and then reduce its
    width and height each by a factor of two.

    For grading purposes, it is important that you use a reflected border
    (i.e., padding equivalent to cv2.BORDER_REFLECT101) and only keep the valid
    region (i.e., the convolution operation should return an image of the same
    shape as the input) for the convolution. Subsampling must include the first
    row and column, skip the second, etc.

    Parameters
    ----------
    image : numpy.ndarray
        A grayscale image of shape (r, c). The array may have any data type
        (e.g., np.uint8, np.float64, etc.)

    kernel : numpy.ndarray (Optional)
        A kernel of shape (N, N). The array may have any data type (e.g.,
        np.uint8, np.float64, etc.)

    Returns
    -------
    numpy.ndarray(dtype=np.float64)
        An image of shape (ceil(r/2), ceil(c/2)). For instance, if the input is
        5x7, the output will be 3x4.
    """

    # WRITE YOUR CODE HERE.
    image = image.astype(np.float64)
    row = len(image)
    col = len(image[0])
    new_img = cv2.filter2D(image,-1,kernel,borderType=cv2.BORDER_REFLECT101)
    new_img = np.delete(new_img, range(1, new_img.shape[0], 2), axis=0)
    new_img = np.delete(new_img, range(1, new_img.shape[1], 2), axis=1)    
    new_img = new_img.astype(np.float64)
    return new_img
    raise NotImplementedError


def expand_layer(image, kernel=generatingKernel(0.4)):
    """Upsample the image to double the row and column dimensions, and then
    convolve it with a generating kernel.

    Upsampling the image means that every other row and every other column will
    have a value of zero. For grading purposes, it is important that you use a 
    reflected border (i.e., padding equivalent to cv2.BORDER_REFLECT101) and only 
    keep the valid region (i.e., the convolution operation should return an image 
    of the same shape as the input) for the convolution.

    Finally, multiply your output image by a factor of 4 in order to scale it
    back up. If you do not do this (and you should try it out without that)
    you will see that your images' brightness changes as you apply the convolution.
    You must explain why this happens in your report PDF.

    Parameters
    ----------
    image : numpy.ndarray
        A grayscale image of shape (r, c). The array may have any data
        type (e.g., np.uint8, np.float64, etc.)

    kernel : numpy.ndarray (Optional)
        A kernel of shape (N, N). The array may have any data
        type (e.g., np.uint8, np.float64, etc.)

    Returns
    -------
    numpy.ndarray(dtype=np.float64)
        An image of shape (2*r, 2*c). For instance, if the input is 3x4, then
        the output will be 6x8.
    """

    # WRITE YOUR CODE HERE.
    image = image.astype(np.float64)
    row = len(image)
    col = len(image[0])
    upsample = np.zeros((2*row,2*col))
    upsample[::2,::2] = image
    new_img = cv2.filter2D(upsample,-1,kernel,borderType=cv2.BORDER_REFLECT101)
    new_img = 4*new_img
    new_img = new_img.astype(np.float64)
    return new_img
    raise NotImplementedError


def gaussPyramid(image, levels):
    """Construct a pyramid from the image by reducing it by the number of
    levels specified by the input.

    Parameters
    ----------
    image : numpy.ndarray
        An image of dimension (r, c).

    levels : int
        A positive integer that specifies the number of reductions to perform.
        For example, levels=0 should return a list containing just the input
        image; levels = 1 should perform one reduction and return a list with
        two images. In general, len(output) = levels + 1.

    Returns
    -------
    list<numpy.ndarray(dtype=np.float)>
        A list of arrays of dtype np.float. The first element of the list
        (output[0]) is layer 0 of the pyramid (the image itself). output[1] is
        layer 1 of the pyramid (image reduced once), etc.
    """

    # WRITE YOUR CODE HERE.
    returnlist = []
    returnlist2 = []
    row = len(image)
    col = len(image[0])
    returnlist2.append(image.astype(np.float))
    if levels == 0:
        return returnlist
    float_image = image.copy()
    for i in range(levels):
        new_img = reduce_layer(float_image)
        # new_img = cv2.GaussianBlur(float_image,(5,5),0)
        # new_img = np.delete(new_img, range(1, new_img.shape[0], 2), axis=0)
        # new_img = np.delete(new_img, range(1, new_img.shape[1], 2), axis=1)
        float_image = new_img.copy()
        returnlist2.append(float_image.astype(np.float))
    return returnlist2
    raise NotImplementedErro


def laplPyramid(gaussPyr):
    """Construct a Laplacian pyramid from a Gaussian pyramid; the constructed
    pyramid will have the same number of levels as the input.

    Parameters
    ----------
    gaussPyr : list<numpy.ndarray(dtype=np.float)>
        A Gaussian Pyramid (as returned by your gaussPyramid function), which
        is a list of numpy.ndarray items.

    Returns
    -------
    list<numpy.ndarray(dtype=np.float)>
        A laplacian pyramid of the same size as gaussPyr. This pyramid should
        be represented in the same way as guassPyr, as a list of arrays. Every
        element of the list now corresponds to a layer of the laplacian
        pyramid, containing the difference between two layers of the gaussian
        pyramid.

        NOTE: The last element of output should be identical to the last layer
              of the input pyramid since it cannot be subtracted anymore.

    Notes
    -----
        (1) Sometimes the size of the expanded image will be larger than the
        given layer. You should crop the expanded image to match in shape with
        the given layer. If you do not do this, you will get a 'ValueError:
        operands could not be broadcast together' because you can't subtract
        differently sized matrices.

        For example, if my layer is of size 5x7, reducing and expanding will
        result in an image of size 6x8. In this case, crop the expanded layer
        to 5x7.
        끝부분 잘라내기
    """

    # WRITE YOUR CODE HERE.
    lplist = []
    for i in range(1,len(gaussPyr)):
        row = len(gaussPyr[i])
        col = len(gaussPyr[i][0])
        temp = expand_layer(gaussPyr[i])
        row2 = len(gaussPyr[i-1])
        col2 = len(gaussPyr[i-1][0])
        temp = temp[0:row2, 0:col2]
        lplp = gaussPyr[i-1] - temp 
        lplp = np.array(lplp,dtype=float)
        lplist.append(lplp)
    lplist.append(gaussPyr[-1])
    return lplist
    raise NotImplementedError


def blend(laplPyrWhite, laplPyrBlack, gaussPyrMask):
    """Blend two laplacian pyramids by weighting them with a gaussian mask.

    You should return a laplacian pyramid that is of the same dimensions as the
    input pyramids. Every layer should be an alpha blend of the corresponding
    layers of the input pyramids, weighted by the gaussian mask.

    Therefore, pixels where current_mask == 1 should be taken completely from
    the white image, and pixels where current_mask == 0 should be taken
    completely from the black image.

    (The variables `current_mask`, `white_image`, and `black_image` refer to
    the images from each layer of the pyramids. This computation must be
    performed for every layer of the pyramid.)

    Parameters
    ----------
    laplPyrWhite : list<numpy.ndarray(dtype=np.float)>
        A laplacian pyramid of an image constructed by your laplPyramid
        function.
    반복문을 돌면서 안에 인덱스를 리사이징해서 다른 피라미드와 같은 사이즈로 만들기
    가우시안 마스크도 사이즈 같게 하기

    laplPyrBlack : list<numpy.ndarray(dtype=np.float)>
        A laplacian pyramid of another image constructed by your laplPyramid
        function.

    gaussPyrMask : list<numpy.ndarray(dtype=np.float)>
        A gaussian pyramid of the mask. Each value should be in the range
        [0, 1].

    Returns
    -------
    list<numpy.ndarray(dtype=np.float)>
        A list containing the blended layers of the two laplacian pyramids

    Notes
    -----
        (1) The input pyramids will always have the same number of levels.
        Furthermore, each layer is guaranteed to have the same shape as
        previous levels.
    """

    # WRITE YOUR CODE HERE.
    returnlist = []
    for lw, lb, mask in zip(laplPyrWhite, laplPyrBlack, gaussPyrMask):
        ls = lw * mask + lb * (1 - mask)
        returnlist.append(ls)
    return returnlist
    raise NotImplementedError


def collapse(pyramid):
    """Collapse an input pyramid.

    Approach this problem as follows: start at the smallest layer of the
    pyramid (at the end of the pyramid list). Expand the smallest layer and
    add it to the second to smallest layer. Then, expand the second to
    smallest layer, and continue the process until you are at the largest
    image. This is your result.

    Parameters
    ----------
    pyramid : list<numpy.ndarray(dtype=np.float)>
        A list of numpy.ndarray images. You can assume the input is taken
        from blend() or laplPyramid().

    Returns
    -------
    numpy.ndarray(dtype=np.float)
        An image of the same shape as the base layer of the pyramid.

    Notes
    -----
        (1) Sometimes expand will return an image that is larger than the next
        layer. In this case, you should crop the expanded image down to the
        size of the next layer. Look into numpy slicing to do this easily.

        For example, expanding a layer of size 3x4 will result in an image of
        size 6x8. If the next layer is of size 5x7, crop the expanded image
        to size 5x7.
    """
    
    # WRITE YOUR CODE HERE.
    init = pyramid[-1]
    for i in range(len(pyramid)-1):
        row, col = init.shape
        temp = expand_layer(init)
        
        newimg = pyramid[-(i+2)]
        row2, col2 = newimg.shape
        temp = temp[0:row2, 0:col2]
        
        init = newimg + temp
    return init
    raise NotImplementedError
